myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"
urlpatterns = [
    path('',views.index,name='index'),
    path('base/',views.base,name="base"),
    path('home/',views.home,name="home"),
    path('profile/',views.profile,name="profile"),
    path('get_demo/',views.get_demo,name="get_demo"),
    path('post_demo/',views.post_demo,name="post_demo"),
    path('register/',views.register,name="register"),
    path('multi/',views.multi,name="multi"),
    path('img_upld/',views.img_upld,name='img_upld'),
    path('image_display/',views.image_display,name='image_display'),
    path('builtin/',views.builtinforms,name="builtinforms")
    
]

uptostatic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/',views.profile,name='profile'),
    path('myapp/',include("myapp.urls")),
    path('base/',views.base,name='base'),
]

if settings.DEBUG==True:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 
    
    

myapp/models.py
from django.db import models

# Create your models here.

myapp/forms.py
from django import forms

choices_day=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')]
choices_month=[('1','JAN'),('2','FEB'),('3','MAR'),('4','APR'),('5','MAY'),('6','JUN'),('7','JUL'),('8','AUG'),('9','SEP'),('10','OCT'),('11','NOV'),('12','DEC')]
choices_year=[('1947', '1947'), ('1948', '1948'), ('1949', '1949'), ('1950', '1950'), ('1951', '1951'), ('1952', '1952'), ('1953', '1953'), ('1954', '1954'), ('1955', '1955'), ('1956', '1956'), ('1957', '1957'), ('1958', '1958'), ('1959', '1959'), ('1960', '1960'), ('1961', '1961'), ('1962', '1962'), ('1963', '1963'), ('1964', '1964'), ('1965', '1965'), ('1966', '1966'), ('1967', '1967'), ('1968', '1968'), ('1969', '1969'), ('1970', '1970'), ('1971', '1971'), ('1972', '1972'), ('1973', '1973'), ('1974', '1974'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')]



class SampleForms(forms.Form):
    first_name=forms.CharField(max_length=20,required=True,label="first name",help_text="NOTE:it does not accepts spl charecters and spaces")
    last_name=forms.CharField(max_length=20,required=False,label="last name")
    email=forms.EmailField(max_length=100,label="Email",required=True)
    phno=forms.IntegerField(max_value=9999999999,min_value=60000000000,label="phone no",required=True)
    pwd=forms.CharField(max_length=20,label="password",required=True,widget=forms.PasswordInput)
    birth_day=forms.ChoiceField(choices=choices_day,label="bitrth day",required=True)
    birth_month=forms.ChoiceField(choices=choices_month,label="birth month",required=True)
    birth_year=forms.ChoiceField(choices=choices_year,label="birth year",required=True)
    gender=forms.ChoiceField(choices=[('Male','Male'),('FeMale','FeMale')],widget=forms.RadioSelect)

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
from django.core.files.storage import FileSystemStorage

# Create your views here.
def index(request):
    return HttpResponse("<h1>WELCOME TO HOME PAGE</h1>")

def base (request):
    return render(request,"base.html")

def home (request):
    return render(request,"myapp/home.html",{"name":"chandu's"})

def profile(request):
    return render(request,"myapp/profile.html",{"name":"chandu's"})

def get_demo(request):
    name=request.GET.get('name')
    return render(request,"get_demo.html",{'name':name})

def post_demo(request):
    if request.method=='POST':
        name=request.POST.get('name')
        return HttpResponse("<h1>thanks for submitting {} as your data".format(name))

    return render(request,"post_demo.html")

def register(request):
    if request.method=='POST':
        first_name=request.POST.get("first_name")
        last_name=request.POST.get("last_name")
        email=request.POST.get("email")
        pwd=request.POST.get("pwd")
        phno=request.POST.get("phno")
        date=request.POST.get("birthday_day")
        month=request.POST.get("birthday_month")
        year=request.POST.get("birthday_year")
        gender=request.POST.get("sex")
        if gender=="1":
            gender="female"

        else:
            gender="male"
            
        send_mail("thanks for registarin", "hello mr./ms.{} {}\n welcome to our world".format(first_name,last_name),
        "pchandramouli92@gmail.com",[email,],fail_silently=False)

        return HttpResponse("{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>".format(first_name,last_name,email,pwd,phno,date,month,year,gender))

    return render(request,"myapp/registrations.html")

def multi(request):
    if request.method=='POST':
        foods=request.POST.getlist("food")
        languages=request.POST.getlist("language")
        return HttpResponse("<h1>{} {}</h1>".format(foods,languages))
    return render(request,"multiselector.html")

def img_upld(request):
    return render(request,"img_upld.html")
    


from myapp.utilities import store_image
    
def image_display(request):
    file_url=False
    if request.method=="POST" and request.FILES:
        image1=request.FILES.get('cm1')
        image2=request.FILES.get('cm2')
        file_urls=map(store_image,[image1,image2])
    return render(request,"image_display.html",context={'file_urls':file_urls})
        


from myapp import forms
def builtinforms(request):
    form=forms.SampleForms()
    return render(request,"builtin.html",{'form':form})
        
            
    

templates/base.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>base page</title>
    {% endblock  %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

  {% include "partials/_header.html "%}
   
    {% block content %}
      

   <div class="container">
        <div class="jumbotron">
          <h1>Welcome to base page</h1>
           
        <a href="{% url 'myapp:home'%}">home</a>
        <a href="{% url 'profile'%}">profile</a>
        <a href="{% url 'base'%}">base</a>
        

        
        
      </div>
    </div> 
      {% endblock  %}
      
      {%include "partials/_cardtitle.html"%}
      {%include "partials/_loveit.html "%}
      
      
{% include "partials/_footer.html "%}

</body>
</html>

templates/builtin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>builtin forms</title>
</head>
<body>
    <form methode="POST">
        {% csrf_token %}
        <!--{{form.as_p}}
        
    ==================================
        <ul>
            {{form.as_ul}}
        </ul>
        ================================-->

        <table border="2px">
            {{form.as_table}}
        </table>
        
        <input  type="submit" value="submit">

    </form>
</body>
</html>

templates/get_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>get demo</title>
</head>
<body>
    <form method="GET">
       
       
       name: <input type="text" placeholder="enter your name" name="name" id="name">
        <input type="submit" value="Submit">
    </form>
    <h1>{{name}}</h1>
    
</body>
</html>

templates/image_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>image display
    </title>
</head>
<body>
    {% for file_url in file_urls %}
    {% if file_url %}
        <img src="{{file_urls}}" alt="no image found" height="200" width="300">
      
    {% endif %}
    {% endfor %}
</body>
</html>

templates/img_upld.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>imgupload</title>
</head>
<body>
    <form action="{% url 'myapp:image_display' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    image:<input type="file" name="cm" id="cm"><br><br>
    image1:<input type="file" name="cm" id="cm"><br><br>
    image2:<input type="file" name="cm" id="cm"><br><br>
    image3:<input type="file" name="cm" id="cm"><br><br>
    <input type="submit" value="submit">
    
    </form>
    
</body>
</html>

templates/multiselector.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" class="form-group">
        {% csrf_token %}
        <label for="langauges">CHOOSE YOUR LANGUAGE:</label>
         <select name="language" id = "languages" multiple>
             <option value="Python">Python</option>
             <option value="Java">Java</option>
             <option value="C#">C#</option>
             <option value="C++">C++</option>
             <option value="C">C</option>
         </select><br>
         <h4>CHOOSE YOUR FOOD</h4>
         <label for="Idli">
             Idli
         </label>
         <input type="checkbox" name="food" id="idli" value="IDLI">
         <label for="Vada">
            Vada
        </label>
        <input type="checkbox" name="food" id="vada" value="VADA">
        <label for="Dosa">
            Dosa
        </label>
        <input type="checkbox" name="food" id="dosa" value="DOSA">
        <label for="Puri">
           Puri
           </label>
        <input type="checkbox" name="food" id="puri" value="PURI"><br>
        <br><input type="submit" value="submit" class="btn btn-primary">

</body>
</html>

templates/myapp/home.html
{% extends "base.html"%}

{% block title %}
    <title>home  page</title>
    {% endblock  %}

    {% block content  %}
    <div class="container">
    <div class="jumbotron">
    <h1>welcom to the {{name}} home page</h1>
   
    <a href="{% url 'profile'%}">profile</a>
    <a href="{% url 'base'%}">base</a>
    </div>
    </div>
    
    {% endblock   %}

templates/myapp/profile.html
{% extends "base.html"%}

{% block title %}
    <title>profile page</title>
    {% endblock  %}

    {% block content  %}
    <div class="container">
        <div class="jumbotron">
    <h1>welcom to the {{name}} profile page</h1>
    <a href="{% url 'base'%}">base</a>
    <a href="{% url 'myapp:home'%}">home</a>
        </div>
        </div>
   
    {% endblock   %}

templates/partials/_cardtitle.html
<div class="card-group">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Card title</h4>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Card title</h4>
        <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Card title</h4>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
      </div>
    </div>
  </div>

templates/partials/_footer.html
<div><nav class="navbar fixed-bottom navbar-dark bg-primary">
    <a class="navbar-brand" href="#!" >end</a>
  </nav>
</div>

templates/partials/_header.html
<div>
    <nav class="navbar fixed-top navbar-dark bg-primary">
        <a class="navbar-brand" href="#!">welcome</a>
        
      </nav>
</div>

templates/partials/_loveit.html
<span class="badge badge-success" >Success</span>
      <div class="input-group">
        <input type="text" class="form-control" placeholder="" aria-label="" aria-describedby="basic-addon1">
        <div class="input-group-append">
          <button class="btn btn-success" type="button">Love it</button>
        </div>
      </div>

templates/post_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>get demo</title>
</head>
<body>
    <form method="POST">
        {% csrf_token%}
        
        NAME:<input type="text" placeholder="enter your data" name="name" id="name">
        <input type="submit" value="submit">
    </form>
    
</body>
</html>